// <auto-generated />
namespace VisualizationWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatesimdatasandcreatenewUserRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatesimdatasandcreatenewUserRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281557448_update simdatas and create new UserRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
