// <auto-generated />
namespace VisualizationWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CityDataHead_Modification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CityDataHead_Modification));
        
        string IMigrationMetadata.Id
        {
            get { return "202101141344260_CityDataHead_Modification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
